title = "Jade's News Feed"
daysOfNews = 60
template = "news.tmpl"
outFile = "docs/index.html"

feeds = [
    "https://jvns.ca/atom.xml",
    "https://rachelbythebay.com/w/atom.xml",
    "https://jade.wtf/index.xml",
    "https://themargins.substack.com/feed.xml",
    "https://cooltrainer.org/feed.xml",
    "https://blog.knightsofthelambdacalcul.us/index.xml",
    "https://solar.lowtechmagazine.com/feeds/all-en.atom.xml",
    "https://jpmens.net/atom.xml",
    "https://dave.cheney.net/feed/atom",
    "https://www.benkuhn.net/index.xml",
    "https://kula.tproa.net/index.xml"
]
