name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      id: go

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Fetch modules
      run: go get ./...

    - name: Test
      run: go test -v .

    - name: Compile
      run: go build
