name: UpdateFeed

on:
  push:
    branches: [ master ]
    paths:
      - '**.tmpl'
      - '**.toml'
  schedule:
    # Run every hour
    - cron: '19 * * * *'

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      id: go

    - name: check out repo
      uses: actions/checkout@v2
    
    - name: Fetch go modules
      run: go get ./...

    - name: Compile
      run: go build

    - name: Fetch feeds
      run: ./jade-news 

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build website (automatic)
        file_pattern: docs/index.html