name: UpdateFeed

on:
  schedule:
    # Run every hour
    - cron: '19 * * * *'

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:

    - name: check out repo
      uses: actions/checkout@v2
    
    - name: Fetch exec
      uses: actions/download-artifact@v2
      with:
        name: exec
        path: jade-news

    - name: Fetch feeds
      run: ./jade-news 

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build website (automatic)
        file_pattern: docs/index.html